import type { CourseCategorySlug } from "./site-config";

export interface Course {
  slug: string;
  title: string;
  price: string;
  priceNote?: string;
  duration: string;
  level: string;
  language: string;
  category: CourseCategorySlug;
  exam?: string;
  includes?: string;
  prerequisite?: string;
  notForBeginners?: string;
  instructor?: string;
  overview: string[];
  whoShouldEnroll?: string[];
  whatYoullLearn?: string[];
  certificateNote?: string;
}

export const courses: Course[] = [
  {
    slug: "bb-glow-certification",
    title: "BB Glow Certification",
    price: "$1,000",
    priceNote: "kit included",
    duration: "2 Days",
    level: "Level 1",
    language: "English",
    category: "skin-facial",
    overview: [
      "Comprehensive training to perform professional BB Glow treatments safely — an advanced skin rejuvenation procedure that enhances natural radiance and evens skin tone.",
      "Covers skin anatomy, skin assessment, product selection, treatment protocols, machine operation, infection prevention, consultation, contraindications, and aftercare.",
    ],
    whoShouldEnroll: [
      "Beginners entering the beauty industry",
      "Estheticians and skincare professionals",
      "Beauty technicians expanding their service menu",
      "Salon, spa, and clinic owners",
    ],
    whatYoullLearn: [
      "Intro to BB Glow",
      "Skin Anatomy & Analysis",
      "Client Consultation & Medical History",
      "Indications & Contraindications",
      "BB Glow Serums & Product Knowledge",
      "Machine Operation & Needle Selection",
      "Treatment Preparation",
      "Step-by-Step Procedure",
      "Health, Safety & Infection Control",
      "Post-Treatment Care",
      "Hands-On Practical Training",
      "Professional Treatment Protocols",
    ],
  },
  {
    slug: "full-body-waxing-certification",
    title: "Full Body Waxing Certification",
    price: "$1,500",
    duration: "3 Days",
    level: "Level 1",
    language: "English",
    category: "waxing-hair-removal",
    overview: [
      "Hands-on training in professional hair removal using industry-standard soft (strip) and hard wax techniques.",
      "Covers client consultation, skin analysis, sanitation and infection control, hair growth cycles, contraindications, pre/post-care, and technique across skin and hair types.",
    ],
    whoShouldEnroll: [
      "Beginners",
      "Estheticians and beauty professionals expanding services",
      "Salon and spa professionals",
      "Aspiring independent beauty business owners",
    ],
    whatYoullLearn: [
      "Intro to Professional Waxing",
      "Hair Growth Cycle & Skin Anatomy",
      "Client Consultation & Health Assessment",
      "Contraindications & Safety",
      "Infection Prevention & Sanitation",
      "Soft & Hard Wax Techniques",
      "Full Body Waxing Procedures",
      "Facial Waxing",
      "Sensitive Area Waxing",
      "Client Positioning & Comfort",
      "Pre/Post-Wax Care",
      "Product & Equipment Knowledge",
      "Hands-On Practical Training",
      "Professional Treatment Protocols",
    ],
  },
  {
    slug: "wax-facial-bb-glow-certification-package",
    title: "Wax, Facial & BB Glow Certification Package",
    price: "$3,500",
    priceNote: "kit included",
    duration: "37 Hours",
    level: "Level 1",
    language: "English",
    category: "skin-facial",
    overview: [
      "Combines three popular treatments — waxing, facial treatments, and BB Glow — into one comprehensive program.",
      "Covers skin analysis, consultation, hygiene and infection control, treatment technique, and product knowledge, with pre and post-care via hands-on training on live models.",
    ],
    whatYoullLearn: [
      "Professional Waxing Techniques",
      "Facial Treatments & Skin Analysis",
      "BB Glow Treatment Procedures",
      "Client Consultation & Safety Protocols",
      "Product Knowledge",
      "Pre/Post-Treatment Care",
      "Hands-On Practical Training",
    ],
    certificateNote: "Certificate upon completion.",
  },
  {
    slug: "brow-lamination-shaping-mapping-certification",
    title: "Brow Lamination, Shaping & Mapping Certification",
    price: "$999",
    duration: "3 Days",
    level: "Level 1",
    language: "English",
    category: "brows-lashes",
    overview: [
      "Teaches fuller, lifted, perfectly shaped eyebrows.",
      "Covers brow anatomy, brow mapping, shaping technique, lamination procedure, product knowledge, consultation, hygiene and safety, and pre/post-care.",
    ],
    whatYoullLearn: [
      "Brow Anatomy & Face Shape Analysis",
      "Brow Mapping & Symmetry",
      "Brow Shaping Techniques",
      "Brow Lamination Procedures",
      "Product Knowledge",
      "Client Consultation & Safety Protocols",
      "Pre/Post-Treatment Care",
      "Hands-On Practical Training",
    ],
    certificateNote: "Certificate upon completion.",
  },
  {
    slug: "beauty-business-management-course",
    title: "Beauty Business Management Course",
    price: "$899",
    duration: "1 Day",
    level: "Level 1",
    language: "English",
    category: "business",
    overview: [
      "For beauty professionals, salon owners, and aspiring entrepreneurs building or growing a beauty business.",
      "Covers business planning, client management, marketing, financial management, and daily operations.",
    ],
    whatYoullLearn: [
      "Business Planning & Goal Setting",
      "Client Service & Relationship Management",
      "Marketing, Branding & Social Media",
      "Financial Management & Budgeting",
      "Pricing & Profitability Strategies",
      "Inventory & Appointment Management",
      "Leadership & Team Development",
      "Business Growth Strategies",
    ],
    certificateNote: "Certificate upon completion.",
  },
  {
    slug: "high-frequency-treatment-certification",
    title: "High Frequency Treatment Certification (Acne)",
    price: "$499",
    duration: "2 Days",
    level: "Level 1",
    language: "English",
    category: "skin-facial",
    overview: [
      "Safe use of high-frequency technology to support acne treatment and skin health — theory plus hands-on practical training.",
    ],
    whatYoullLearn: [
      "Intro to High-Frequency Technology",
      "Skin Anatomy & Acne Assessment",
      "Client Consultation & Safety Protocols",
      "Equipment Operation",
      "Acne Treatment Procedures",
      "Hygiene & Infection Prevention",
      "Pre/Post-Treatment Care",
      "Hands-On Practical Training",
    ],
    certificateNote: "Certificate upon completion.",
  },
  {
    slug: "advanced-microneedling-certification",
    title: "Advanced Microneedling Certification",
    price: "$999",
    priceNote: "kit included",
    duration: "2 Days",
    level: "Level 1",
    language: "English",
    category: "skin-facial",
    overview: [
      "Professional microneedling for skin texture, fine lines, acne scars, enlarged pores, pigmentation, and collagen production.",
    ],
    whatYoullLearn: [
      "Intro to Microneedling & Collagen Induction Therapy",
      "Skin Anatomy & Assessment",
      "Client Consultation & Treatment Planning",
      "Microneedling Techniques & Device Operation",
      "Contraindications & Safety",
      "Hygiene & Infection Prevention",
      "Pre/Post-Treatment Care",
      "Hands-On Practical Training",
    ],
    certificateNote: "Certificate upon completion.",
  },
  {
    slug: "dermaplaning-certification",
    title: "Dermaplaning Certification",
    price: "$799",
    duration: "2 Days",
    level: "Level 1",
    language: "English",
    category: "skin-facial",
    overview: ["Safe, effective dermaplaning exfoliation treatment — theory plus hands-on training."],
    whatYoullLearn: [
      "Intro to Dermaplaning",
      "Skin Anatomy & Assessment",
      "Client Consultation & Treatment Planning",
      "Safe Blade Handling & Technique",
      "Contraindications & Safety",
      "Hygiene & Infection Prevention",
      "Pre/Post-Treatment Care",
      "Hands-On Practical Training",
    ],
    certificateNote: "Certificate upon completion.",
  },
  {
    slug: "microdermabrasion-certification",
    title: "Microdermabrasion Certification",
    price: "$499",
    duration: "2 Days",
    level: "Level 1",
    language: "English",
    category: "skin-facial",
    overview: [
      "Safe, effective microdermabrasion for texture, brightening, fine lines, mild acne scars, enlarged pores, and uneven tone.",
    ],
    whatYoullLearn: [
      "Intro to Microdermabrasion",
      "Skin Anatomy & Assessment",
      "Client Consultation & Treatment Planning",
      "Machine Operation",
      "Treatment Technique & Safety",
      "Hygiene & Infection Prevention",
      "Pre/Post-Treatment Care",
      "Hands-On Practical Training",
    ],
    certificateNote: "Certificate upon completion.",
  },
  {
    slug: "skin-analysis-certification",
    title: "Skin Analysis Certification",
    price: "$499",
    duration: "3 Days",
    level: "Level 1",
    language: "English",
    category: "skin-facial",
    overview: ["Accurately assess skin types and conditions and recommend appropriate treatments and products."],
    whatYoullLearn: [
      "Skin Anatomy & Types",
      "Professional Skin Analysis Techniques",
      "Client Consultation & Assessment",
      "Common Skin Conditions & Contraindications",
      "Product & Treatment Recommendations",
      "Professional Hygiene & Safety",
      "Hands-On Practical Training",
    ],
    certificateNote: "Certificate upon completion.",
  },
  {
    slug: "microblading-certification",
    title: "Microblading Certification",
    price: "$1,499",
    priceNote: "kit included",
    duration: "2 Days",
    level: "Level 1",
    language: "English",
    category: "pmu",
    overview: ["Professional semi-permanent eyebrow enhancement via manual microblading."],
    whatYoullLearn: [
      "Intro to Microblading",
      "Brow Mapping & Facial Symmetry",
      "Color Theory & Pigment Selection",
      "Skin Types & Client Assessment",
      "Manual Tool Handling & Stroke Technique",
      "Contraindications & Safety",
      "Hygiene & Infection Prevention",
      "Pre/Post-Treatment Care",
      "Hands-On Practical Training",
    ],
    certificateNote: "Certificate upon completion.",
  },
  {
    slug: "lash-lift-tint-certification",
    title: "Lash Lift & Tint Certification",
    price: "$599",
    duration: "2 Days",
    level: "Level 1",
    language: "English",
    category: "brows-lashes",
    overview: ["Enhance natural lashes (no extensions) — lifted, curled, tinted results."],
    whatYoullLearn: [
      "Intro to Lash Lift & Tint",
      "Lash Anatomy & Eye Shape Assessment",
      "Product Knowledge & Shield Selection",
      "Client Consultation & Treatment Planning",
      "Lash Lift & Tint Techniques",
      "Hygiene & Safety Protocols",
      "Pre/Post-Treatment Care",
      "Hands-On Practical Training",
    ],
    certificateNote: "Certificate upon completion.",
  },
  {
    slug: "lip-blush-pmu-certification",
    title: "Lip Blush PMU Certification",
    price: "$1,499",
    duration: "2 Days",
    level: "Level 1",
    language: "English",
    category: "pmu",
    overview: ["Semi-permanent lip enhancement for natural color, shape, and definition."],
    whatYoullLearn: [
      "Intro to Lip Blush PMU",
      "Lip Anatomy & Color Theory",
      "Pigment Selection & Color Correction",
      "Client Consultation & Treatment Planning",
      "PMU Machine Operation & Application",
      "Contraindications & Safety",
      "Hygiene & Infection Prevention",
      "Pre/Post-Treatment Care",
      "Hands-On Practical Training",
    ],
    certificateNote: "Certificate upon completion.",
  },
  {
    slug: "self-makeup-certification",
    title: "Self-Makeup Certification",
    price: "$599",
    duration: "2 Days",
    level: "Level 1",
    language: "English",
    category: "makeup-hair",
    overview: ["For beginners and enthusiasts — everyday and special-occasion makeup application."],
    whatYoullLearn: [
      "Skin Preparation & Product Selection",
      "Foundation Matching & Color Correction",
      "Contouring & Highlighting",
      "Eye Makeup Techniques",
      "Eyebrow Shaping",
      "Lip Application",
      "Makeup Tools & Hygiene",
      "Hands-On Practical Training",
    ],
    certificateNote: "Certificate upon completion.",
  },
  {
    slug: "sugaring-certification-course",
    title: "Sugaring Certification Course",
    price: "$1,195",
    duration: "2 Days",
    level: "Level 1",
    language: "English",
    category: "waxing-hair-removal",
    exam: "Written",
    includes: "Theory & Practical Manual",
    instructor: "Jen Barnes, Tamara's Sugar Western Canada",
    overview: [
      "Taught by Jen Barnes of Tamara's Sugar Western Canada.",
      "Covers sugaring theory and history, product knowledge and protocol, demo plus hands-on practice on models, an essential sugaring starter kit, and ongoing instructor support after the course.",
      "Class length may vary with class size and discussion.",
    ],
  },
  {
    slug: "powder-ombre-shading-certification-course",
    title: "Powder Ombre Shading Certification Course",
    price: "$995",
    duration: "1 Day",
    level: "Level 1",
    language: "English",
    category: "pmu",
    exam: "Written",
    includes: "Theory & Practical Manual",
    prerequisite: "Must be Microblading Certified.",
    overview: [
      "Covers powder ombre shading technique and procedure, maximum retention, pre/post-care, and color correction.",
    ],
    certificateNote: "Certificate given on completion.",
  },
  {
    slug: "heena-henna-certification",
    title: "Heena (Henna) Certification",
    price: "$995",
    duration: "—",
    level: "Level 1",
    language: "English",
    category: "makeup-hair",
    includes: "Practical Training",
    overview: ["Professional henna application technique, designs, and product use through hands-on training."],
  },
  {
    slug: "eyelash-extension-certification",
    title: "Eyelash Extension Certification",
    price: "$999",
    priceNote: "kit included",
    duration: "3 Days",
    level: "Level 1",
    language: "English",
    category: "brows-lashes",
    includes: "Practical Training",
    overview: [
      "Lash preparation, isolation, safe application, styling, and mapping.",
      "Covers adhesive use, removal, aftercare, hygiene, and client safety.",
    ],
  },
  {
    slug: "advanced-hair-cutting-course",
    title: "Advanced Hair-Cutting Course",
    price: "$999",
    duration: "3 Days",
    level: "Level 1",
    language: "English",
    category: "makeup-hair",
    includes: "Practical Training",
    notForBeginners: "Not suitable for beginners — requires existing basic haircutting knowledge.",
    overview: [
      "Advanced techniques: long, medium, and short layers, face-framing, shaping, blending, and precision cutting.",
    ],
  },
  {
    slug: "eyebrow-tinting-shaping-certification",
    title: "Eyebrow Tinting & Shaping Certification",
    price: "$699",
    duration: "—",
    level: "Level 1",
    language: "English",
    category: "brows-lashes",
    includes: "Practical Training",
    overview: [
      "Brow consultation, color selection, and professional tint application.",
      "Covers shaping, mapping, waxing and tweezing, symmetry, hygiene, safety, and aftercare.",
    ],
  },
  {
    slug: "eyebrow-threading-certification",
    title: "Eyebrow Threading Certification",
    price: "$1,199",
    duration: "—",
    level: "Level 1",
    language: "English",
    category: "brows-lashes",
    includes: "Practical Training",
    overview: ["Thread handling, brow shaping and mapping, hair-removal technique, consultation, hygiene, safety, and aftercare."],
  },
  {
    slug: "permanent-makeup-certification",
    title: "Permanent Make-up Certification",
    price: "$3,999",
    priceNote: "kit included",
    duration: "3 Days",
    level: "Level 1",
    language: "English",
    category: "pmu",
    includes: "Practical Training",
    overview: [
      "Client consultation, facial and brow mapping, color theory, and pigment selection.",
      "Covers skin prep, machine and tool handling, application technique, hygiene and sanitation, client safety, and aftercare.",
    ],
    certificateNote:
      "Certificate: Permanent Makeup (PMU) Certification from Nag's Beauty Supplies & Training Centre.",
  },
];

export function getCourseBySlug(slug: string): Course | undefined {
  return courses.find((c) => c.slug === slug);
}

export function getCoursesByCategory(category: CourseCategorySlug): Course[] {
  return courses.filter((c) => c.category === category);
}
